// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmi42fQiRNTXXVat3H6XzmX_zjaetv5EU',
    appId: '1:638666852369:web:3d6adef1838fc3508d89b0',
    messagingSenderId: '638666852369',
    projectId: 'medlink-2f073',
    authDomain: 'medlink-2f073.firebaseapp.com',
    storageBucket: 'medlink-2f073.appspot.com',
    measurementId: 'G-7DC9ZC32EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3eaXMVQ2P9tH4f662js5dYtH6e8fSDoA',
    appId: '1:638666852369:android:2ca35ac187e2eebd8d89b0',
    messagingSenderId: '638666852369',
    projectId: 'medlink-2f073',
    storageBucket: 'medlink-2f073.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4T8d8qZMuQAzpVSIh6ydyrSWF1JV3Vf8',
    appId: '1:638666852369:ios:47ebb9908a2557228d89b0',
    messagingSenderId: '638666852369',
    projectId: 'medlink-2f073',
    storageBucket: 'medlink-2f073.appspot.com',
    iosClientId: '638666852369-qimm3uu796rdaun5r1gdp4u8md1umj70.apps.googleusercontent.com',
    iosBundleId: 'com.example.medlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4T8d8qZMuQAzpVSIh6ydyrSWF1JV3Vf8',
    appId: '1:638666852369:ios:47ebb9908a2557228d89b0',
    messagingSenderId: '638666852369',
    projectId: 'medlink-2f073',
    storageBucket: 'medlink-2f073.appspot.com',
    iosClientId: '638666852369-qimm3uu796rdaun5r1gdp4u8md1umj70.apps.googleusercontent.com',
    iosBundleId: 'com.example.medlink',
  );
}
